// <auto-generated />
namespace ParkingManagerServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3423k4jksdjfasdf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3423k4jksdjfasdf));
        
        string IMigrationMetadata.Id
        {
            get { return "201711180107193_3423k4jksdjfasdf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
