#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ParkingApp.Resource", IsApplication=true)]

namespace ParkingApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Car = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int button1 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int button2 = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int editText1 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int editText2 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int editText3 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int editText4 = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int gridLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int imageView1 = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int space1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int space2 = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int space3 = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int space4 = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView3 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView4 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textView5 = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TelaCadastro = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TelaLogin = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
